[platformio]
default_envs = uno_active_high

[env]
platform = atmelavr
framework = arduino
monitor_speed = 9600
build_flags =
    -Wall
    -Wextra
    -DINPUT_ACTIVE_LOW=0

[env:uno_active_high]
board = uno

[env:uno_internal_pullup]
board = uno
build_unflags = -DINPUT_ACTIVE_LOW=0
build_flags =
    ${env.build_flags}
    -DINPUT_ACTIVE_LOW=1
